version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: komvos_mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # <-- O volume é USADO aqui
    networks:
      - komvos_network

  komvosmind_ai:
    build: .
    container_name: komvosmind_ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - komvos_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - komvos_network

networks:
  komvos_network:
    external: false

volumes:
  qdrant_storage:
  mysql_data: # <-- O volume é DECLARADO aqui
