version: "3.8"

services:
  komvosmind_ai:
    build: .
    container_name: komvosmind_ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://komvosmind_ai:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - komvos_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - komvos_network

networks:
  komvos_network:
    external: true
    name: komvos_network   # <— importante

volumes:
  qdrant_storage:
