// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20250915083133_PrimeiraMigrationTenant")]
    partial class PrimeiraMigrationTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgentFile", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FilesId")
                        .HasColumnType("char(36)");

                    b.HasKey("AgentsId", "FilesId");

                    b.HasIndex("FilesId");

                    b.ToTable("AgentFile");
                });

            modelBuilder.Entity("AgentKnowledge", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KnowledgesId")
                        .HasColumnType("char(36)");

                    b.HasKey("AgentsId", "KnowledgesId");

                    b.HasIndex("KnowledgesId");

                    b.ToTable("AgentKnowledge");
                });

            modelBuilder.Entity("AgentSeniorErpConfig", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SeniorErpConfigsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AgentsId", "SeniorErpConfigsId");

                    b.HasIndex("SeniorErpConfigsId");

                    b.ToTable("AgentSeniorErpConfig");
                });

            modelBuilder.Entity("AgentSeniorHcmConfig", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SeniorHcmConfigsId")
                        .HasColumnType("char(36)");

                    b.HasKey("AgentsId", "SeniorHcmConfigsId");

                    b.HasIndex("SeniorHcmConfigsId");

                    b.ToTable("AgentSeniorHcmConfig");
                });

            modelBuilder.Entity("Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Module")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdChatSession")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdChatSession");

                    b.ToTable("ChatHistory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdAgent")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("LastSendDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalInteractions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAgent");

                    b.ToTable("ChatSessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("AddressNumber")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CollaboratorTypeCodeSeniorTipeCol")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CompanyCodSeniorNumEmp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<decimal?>("ComplementarySalary")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("CostCenterCodSeniorCodCcu")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CostCneterName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeCodSeniorNumCad")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid>("IdKnowledge")
                        .HasColumnType("char(36)");

                    b.Property<string>("PostalCode")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Race")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime?>("SalaryEffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusCodSenior")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("StatusDescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdKnowledge");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .IsUnicode(false)
                        .HasColumnType("LONGTEXT");

                    b.Property<int?>("CompletionTime")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsUnicode(false)
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Module")
                        .HasColumnType("int");

                    b.Property<int?>("PromptTime")
                        .HasColumnType("int");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<int?>("QueueTime")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsUnicode(false)
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("TotalPages")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int?>("TotalTime")
                        .HasColumnType("int");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("File", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("Module")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int?>("Origin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Knowledge", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangedEntity")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastState")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameUser")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeProcess")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdFile")
                        .HasColumnType("char(36)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("ResumePage")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("IdFile");

                    b.ToTable("Page", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CalculationTypeCodSeniorTipCal")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CalculationTypeName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CollaboratorTypeCodeSeniorTipCol")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CompanyCodSeniorNumEmp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeCodSeniorNumCad")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<decimal?>("EventAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EventCodSeniorCodenv")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("EventTypeCodSeniorTipEve")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("EventTypeName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("IdEmployee")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("PayrollPeriodCod")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("PayrollPeriodCodSeniorCodCal")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime?>("ReferenceDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdEmployee");

                    b.ToTable("Payroll", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SalaryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("date");

                    b.Property<string>("CompanyCodSeniorCodFil")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("CompanyCodSeniorNumEmp")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeCodSeniorNumCad")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("IdEmployee")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("MotiveCodSeniorCodMot")
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("MotiveName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<decimal>("NewSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmployee");

                    b.ToTable("SalaryHistory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SeniorErpConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("WsdlUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.ToTable("SeniorErpConfig", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SeniorHcmConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("WsdlUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.ToTable("SeniorHcmConfig", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TwilioConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountSid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdAgent")
                        .HasColumnType("char(36)");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("IdAgent");

                    b.ToTable("TwilioConfig", (string)null);
                });

            modelBuilder.Entity("AgentFile", b =>
                {
                    b.HasOne("Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentKnowledge", b =>
                {
                    b.HasOne("Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.Knowledge", null)
                        .WithMany()
                        .HasForeignKey("KnowledgesId")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentSeniorErpConfig", b =>
                {
                    b.HasOne("Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.SeniorErpConfig", null)
                        .WithMany()
                        .HasForeignKey("SeniorErpConfigsId")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentSeniorHcmConfig", b =>
                {
                    b.HasOne("Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .IsRequired();

                    b.HasOne("Domain.Entities.SeniorHcmConfig", null)
                        .WithMany()
                        .HasForeignKey("SeniorHcmConfigsId")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ChatHistory", b =>
                {
                    b.HasOne("Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatHistory")
                        .HasForeignKey("IdChatSession")
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("Domain.Entities.Agent", "Agent")
                        .WithMany("Chats")
                        .HasForeignKey("IdAgent")
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Knowledge", "Knowledge")
                        .WithMany()
                        .HasForeignKey("IdKnowledge")
                        .IsRequired();

                    b.Navigation("Knowledge");
                });

            modelBuilder.Entity("Domain.Entities.Page", b =>
                {
                    b.HasOne("Domain.Entities.File", "File")
                        .WithMany("Pages")
                        .HasForeignKey("IdFile");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Domain.Entities.Payroll", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("IdEmployee")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.SalaryHistory", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("IdEmployee")
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.TwilioConfig", b =>
                {
                    b.HasOne("Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("IdAgent")
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Domain.Entities.Agent", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatHistory");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Payrolls");

                    b.Navigation("SalaryHistories");
                });

            modelBuilder.Entity("Domain.Entities.File", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
